"""empty message

Revision ID: 0019635491c4
Revises: 9e930f40f0cb
Create Date: 2023-08-04 22:50:19.845356

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0019635491c4"
down_revision = "9e930f40f0cb"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("symbol", table_name="fundamentals")
    op.drop_table("fundamentals")
    # ### end Alembic commands ###


@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fundamentals",
        sa.Column("longBusinessSummary", mysql.LONGTEXT(), nullable=True),
        sa.Column("companyOfficers", mysql.TEXT(), nullable=True),
        sa.Column("marketCap", mysql.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("floatShares", mysql.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "sharesOutstanding", mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "impliedSharesOutstanding",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("symbol", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("address1", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("city", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("state", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("zip_code", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("country", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("phone", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("website", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("industry", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("industryDisp", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("sector", mysql.VARCHAR(length=255), nullable=True),
        sa.Column(
            "fullTimeEmployees", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("auditRisk", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("boardRisk", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "compensationRisk", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "shareHolderRightsRisk", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("overallRisk", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("governanceEpochDate", mysql.VARCHAR(length=255), nullable=True),
        sa.Column(
            "compensationAsOfEpochDate", mysql.VARCHAR(length=255), nullable=True
        ),
        sa.Column("maxAge", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("priceHint", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("previousClose", mysql.FLOAT(), nullable=True),
        sa.Column("open", mysql.FLOAT(), nullable=True),
        sa.Column("dayLow", mysql.FLOAT(), nullable=True),
        sa.Column("dayHigh", mysql.FLOAT(), nullable=True),
        sa.Column("regularMarketPreviousClose", mysql.FLOAT(), nullable=True),
        sa.Column("regularMarketOpen", mysql.FLOAT(), nullable=True),
        sa.Column("regularMarketDayLow", mysql.FLOAT(), nullable=True),
        sa.Column("regularMarketDayHigh", mysql.FLOAT(), nullable=True),
        sa.Column("dividendRate", mysql.FLOAT(), nullable=True),
        sa.Column("dividendYield", mysql.FLOAT(), nullable=True),
        sa.Column("exDividendDate", mysql.DATETIME(), nullable=True),
        sa.Column("payoutRatio", mysql.FLOAT(), nullable=True),
        sa.Column("fiveYearAvgDividendYield", mysql.FLOAT(), nullable=True),
        sa.Column("beta", mysql.FLOAT(), nullable=True),
        sa.Column("trailingPE", mysql.FLOAT(), nullable=True),
        sa.Column("forwardPE", mysql.FLOAT(), nullable=True),
        sa.Column("volume", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "regularMarketVolume", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("averageVolume", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "averageVolume10days", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "averageDailyVolume10Day",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("bid", mysql.FLOAT(), nullable=True),
        sa.Column("ask", mysql.FLOAT(), nullable=True),
        sa.Column("bidSize", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("askSize", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fiftyTwoWeekLow", mysql.FLOAT(), nullable=True),
        sa.Column("fiftyTwoWeekHigh", mysql.FLOAT(), nullable=True),
        sa.Column("priceToSalesTrailing12Months", mysql.FLOAT(), nullable=True),
        sa.Column("fiftyDayAverage", mysql.FLOAT(), nullable=True),
        sa.Column("twoHundredDayAverage", mysql.FLOAT(), nullable=True),
        sa.Column("trailingAnnualDividendRate", mysql.FLOAT(), nullable=True),
        sa.Column("trailingAnnualDividendYield", mysql.FLOAT(), nullable=True),
        sa.Column("currency", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("enterpriseValue", mysql.FLOAT(), nullable=True),
        sa.Column("profitMargins", mysql.FLOAT(), nullable=True),
        sa.Column("sharesShort", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "sharesShortPriorMonth", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "sharesShortPreviousMonthDate",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("dateShortInterest", mysql.DATETIME(), nullable=True),
        sa.Column("sharesPercentSharesOut", mysql.FLOAT(), nullable=True),
        sa.Column("heldPercentInsiders", mysql.FLOAT(), nullable=True),
        sa.Column("heldPercentInstitutions", mysql.FLOAT(), nullable=True),
        sa.Column("shortRatio", mysql.FLOAT(), nullable=True),
        sa.Column("shortPercentOfFloat", mysql.FLOAT(), nullable=True),
        sa.Column("bookValue", mysql.FLOAT(), nullable=True),
        sa.Column("priceToBook", mysql.FLOAT(), nullable=True),
        sa.Column("lastFiscalYearEnd", mysql.FLOAT(), nullable=True),
        sa.Column("nextFiscalYearEnd", mysql.FLOAT(), nullable=True),
        sa.Column("mostRecentQuarter", mysql.FLOAT(), nullable=True),
        sa.Column("earningsQuarterlyGrowth", mysql.FLOAT(), nullable=True),
        sa.Column("netIncomeToCommon", mysql.FLOAT(), nullable=True),
        sa.Column("trailingEps", mysql.FLOAT(), nullable=True),
        sa.Column("forwardEps", mysql.FLOAT(), nullable=True),
        sa.Column("pegRatio", mysql.FLOAT(), nullable=True),
        sa.Column("lastSplitFactor", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("lastSplitDate", mysql.DATETIME(), nullable=True),
        sa.Column("enterpriseToRevenue", mysql.FLOAT(), nullable=True),
        sa.Column("enterpriseToEbitda", mysql.FLOAT(), nullable=True),
        sa.Column("FiftyTwoWeekChange", mysql.FLOAT(), nullable=True),
        sa.Column("SandP52WeekChange", mysql.FLOAT(), nullable=True),
        sa.Column("lastDividendValue", mysql.FLOAT(), nullable=True),
        sa.Column("lastDividendDate", mysql.DATETIME(), nullable=True),
        sa.Column("exchange", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("quoteType", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("underlyingSymbol", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("shortName", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("longName", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("firstTradeDateEpochUtc", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("timeZoneFullName", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("timeZoneShortName", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("uuid", mysql.VARCHAR(length=255), nullable=True),
        sa.Column(
            "messageBoardId", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "gmtOffSetMilliseconds", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("currentPrice", mysql.FLOAT(), nullable=True),
        sa.Column("targetHighPrice", mysql.FLOAT(), nullable=True),
        sa.Column("targetLowPrice", mysql.FLOAT(), nullable=True),
        sa.Column("targetMeanPrice", mysql.FLOAT(), nullable=True),
        sa.Column("targetMedianPrice", mysql.FLOAT(), nullable=True),
        sa.Column("recommendationMean", mysql.FLOAT(), nullable=True),
        sa.Column("recommendationKey", mysql.FLOAT(), nullable=True),
        sa.Column("numberOfAnalystOpinions", mysql.FLOAT(), nullable=True),
        sa.Column("totalCash", mysql.FLOAT(), nullable=True),
        sa.Column("totalCashPerShare", mysql.FLOAT(), nullable=True),
        sa.Column("ebitda", mysql.FLOAT(), nullable=True),
        sa.Column("totalDebt", mysql.FLOAT(), nullable=True),
        sa.Column("quickRatio", mysql.FLOAT(), nullable=True),
        sa.Column("currentRatio", mysql.FLOAT(), nullable=True),
        sa.Column("totalRevenue", mysql.FLOAT(), nullable=True),
        sa.Column("debtToEquity", mysql.FLOAT(), nullable=True),
        sa.Column("revenuePerShare", mysql.FLOAT(), nullable=True),
        sa.Column("returnOnAssets", mysql.FLOAT(), nullable=True),
        sa.Column("returnOnEquity", mysql.FLOAT(), nullable=True),
        sa.Column("grossProfits", mysql.FLOAT(), nullable=True),
        sa.Column("freeCashflow", mysql.FLOAT(), nullable=True),
        sa.Column("operatingCashflow", mysql.FLOAT(), nullable=True),
        sa.Column("earningsGrowth", mysql.FLOAT(), nullable=True),
        sa.Column("revenueGrowth", mysql.FLOAT(), nullable=True),
        sa.Column("grossMargins", mysql.FLOAT(), nullable=True),
        sa.Column("ebitdaMargins", mysql.FLOAT(), nullable=True),
        sa.Column("operatingMargins", mysql.FLOAT(), nullable=True),
        sa.Column("financialCurrency", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("trailingPegRatio", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("fax", mysql.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("symbol", "fundamentals", ["symbol"], unique=False)
    # ### end Alembic commands ###
