"""empty message

Revision ID: 024d9269b054
Revises: 7a08e9cab5db
Create Date: 2023-08-05 13:45:05.465156

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end


# revision identifiers, used by Alembic.
revision = "024d9269b054"
down_revision = "7a08e9cab5db"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
