"""empty message

Revision ID: 2600c2b9dfef
Revises: 0a0d5dfcd2a7
Create Date: 2023-08-16 20:58:34.535348

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2600c2b9dfef'
down_revision = '0a0d5dfcd2a7'
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)

@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_daily_price', 'vendor_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('fact_daily_price', 'adj_close',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('fact_one_min_price', 'vendor_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###

@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_one_min_price', 'vendor_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('fact_daily_price', 'adj_close',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('fact_daily_price', 'vendor_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
