"""empty message

Revision ID: 2720618578ea
Revises: e9abaf502ff3
Create Date: 2023-08-02 21:29:01.036181

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end


# revision identifiers, used by Alembic.
revision = "2720618578ea"
down_revision = "e9abaf502ff3"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fact_daily_price",
        sa.Column("vendor_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(
        None, "fact_daily_price", "dim_data_vendor", ["vendor_name"], ["name"]
    )
    # ### end Alembic commands ###


@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "fact_daily_price", type_="foreignkey")
    op.drop_column("fact_daily_price", "vendor_name")
    # ### end Alembic commands ###
