"""empty message

Revision ID: 3ecbf9ca462f
Revises: c4cb0550db7b
Create Date: 2023-08-11 23:07:56.653672

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ecbf9ca462f'
down_revision = 'c4cb0550db7b'
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)

@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dim_companies_symbol', table_name='dim_companies')
    op.create_index(op.f('ix_dim_companies_symbol'), 'dim_companies', ['symbol'], unique=True)
    op.drop_index('vendor_name', table_name='dim_data_vendor')
    op.drop_index('ix_dim_data_vendor_vendor_name', table_name='dim_data_vendor')
    op.create_index(op.f('ix_dim_data_vendor_vendor_name'), 'dim_data_vendor', ['vendor_name'], unique=True)
    op.drop_column('fact_one_min_price', 'adj_close')
    # ### end Alembic commands ###

@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_one_min_price', sa.Column('adj_close', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_dim_data_vendor_vendor_name'), table_name='dim_data_vendor')
    op.create_index('ix_dim_data_vendor_vendor_name', 'dim_data_vendor', ['vendor_name'], unique=False)
    op.create_index('vendor_name', 'dim_data_vendor', ['vendor_name'], unique=False)
    op.drop_index(op.f('ix_dim_companies_symbol'), table_name='dim_companies')
    op.create_index('ix_dim_companies_symbol', 'dim_companies', ['symbol'], unique=False)
    # ### end Alembic commands ###
