"""empty message

Revision ID: 46f73fa99f89
Revises: 29ca995cdc8f
Create Date: 2023-08-02 23:10:03.858198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "46f73fa99f89"
down_revision = "29ca995cdc8f"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dim_data_vendor",
        "vendor_name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_index("ix_dim_data_vendor_name", table_name="dim_data_vendor")
    # ### end Alembic commands ###


@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_dim_data_vendor_name", "dim_data_vendor", ["vendor_name"], unique=False
    )
    op.alter_column(
        "dim_data_vendor",
        "vendor_name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###
