"""empty message

Revision ID: 7a08e9cab5db
Revises: 0019635491c4
Create Date: 2023-08-04 23:57:58.370901

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end


# revision identifiers, used by Alembic.
revision = "7a08e9cab5db"
down_revision = "0019635491c4"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dim_companies",
        sa.Column("vendor_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(
        None, "dim_companies", "dim_data_vendor", ["vendor_name"], ["vendor_name"]
    )
    # ### end Alembic commands ###


@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "dim_companies", type_="foreignkey")
    op.drop_column("dim_companies", "vendor_name")
    # ### end Alembic commands ###
