"""empty message

Revision ID: 7d270548be60
Revises: a68498f4955d
Create Date: 2023-08-01 21:29:53.043690

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d270548be60'
down_revision = 'a68498f4955d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_data_vendor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_daily_price',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_vendor_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_vendor_id'], ['dim_data_vendor.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['dim_companies.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Daily stock price of public listed companies'
    )
    op.drop_table('dim_datavendor')
    op.drop_table('fact_historical_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_historical_price',
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('open', mysql.FLOAT(), nullable=True),
    sa.Column('high', mysql.FLOAT(), nullable=True),
    sa.Column('low', mysql.FLOAT(), nullable=True),
    sa.Column('close', mysql.FLOAT(), nullable=True),
    sa.Column('adj_close', mysql.FLOAT(), nullable=True),
    sa.Column('volume', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['dim_companies.symbol'], name='fact_historical_price_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='Historical stock price of public listed companies',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='Historical stock price of public listed companies',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dim_datavendor',
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('website_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('support_email', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('fact_daily_price')
    op.drop_table('dim_data_vendor')
    # ### end Alembic commands ###
