"""empty message

Revision ID: 7de8d9d52cba
Revises: f2c582378374
Create Date: 2023-08-16 20:29:02.989702

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end


# revision identifiers, used by Alembic.
revision = '7de8d9d52cba'
down_revision = 'f2c582378374'
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)

@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
