"""empty message

Revision ID: 87bbd5fd5d0d
Revises: 37d40532472d
Create Date: 2023-08-02 21:02:12.670904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87bbd5fd5d0d'
down_revision = '37d40532472d'
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)

@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fact_daily_price_ibfk_1', 'fact_daily_price', type_='foreignkey')
    op.drop_column('fact_daily_price', 'data_vendor_id')
    # ### end Alembic commands ###

@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_daily_price', sa.Column('data_vendor_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fact_daily_price_ibfk_1', 'fact_daily_price', 'dim_data_vendor', ['data_vendor_id'], ['id'])
    # ### end Alembic commands ###
