"""empty message

Revision ID: 88c3dda9e500
Revises: 87bbd5fd5d0d
Create Date: 2023-08-02 21:19:32.787890

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end


# revision identifiers, used by Alembic.
revision = '88c3dda9e500'
down_revision = '87bbd5fd5d0d'
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)

@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dim_data_vendor_name'), 'dim_data_vendor', ['name'], unique=False)
    # ### end Alembic commands ###

@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dim_data_vendor_name'), table_name='dim_data_vendor')
    # ### end Alembic commands ###
