"""empty message

Revision ID: 99dc8fe6ac5f
Revises: 63fcda26eefe
Create Date: 2023-08-11 22:51:59.059335

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "99dc8fe6ac5f"
down_revision = "63fcda26eefe"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dim_companies_symbol", table_name="dim_companies")
    op.create_index(
        op.f("ix_dim_companies_symbol"), "dim_companies", ["symbol"], unique=True
    )
    # op.drop_column('fact_one_min_price', 'adj_close')
    # ### end Alembic commands ###


@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fact_one_min_price", sa.Column("adj_close", mysql.FLOAT(), nullable=True)
    )
    op.drop_index(op.f("ix_dim_companies_symbol"), table_name="dim_companies")
    op.create_index(
        "ix_dim_companies_symbol", "dim_companies", ["symbol"], unique=False
    )
    # ### end Alembic commands ###
