"""empty message

Revision ID: 9e930f40f0cb
Revises: e54230721057
Create Date: 2023-08-02 23:53:04.218173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9e930f40f0cb"
down_revision = "e54230721057"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dim_data_vendor",
        "vendor_name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_index("ix_dim_data_vendor_name", table_name="dim_data_vendor")
    op.create_index(
        op.f("ix_dim_data_vendor_vendor_name"),
        "dim_data_vendor",
        ["vendor_name"],
        unique=False,
    )
    op.create_table_comment(
        "dim_data_vendor",
        "List of data vendor sources",
        existing_comment=None,
        schema=None,
    )
    # ### end Alembic commands ###


@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        "dim_data_vendor", existing_comment="List of data vendor sources", schema=None
    )
    op.drop_index(op.f("ix_dim_data_vendor_vendor_name"), table_name="dim_data_vendor")
    op.create_index(
        "ix_dim_data_vendor_name", "dim_data_vendor", ["vendor_name"], unique=False
    )
    op.alter_column(
        "dim_data_vendor",
        "vendor_name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###
