"""empty message

Revision ID: a72179fc3faf
Revises: f58fb3345d3a
Create Date: 2023-08-16 00:09:26.278747

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a72179fc3faf'
down_revision = 'f58fb3345d3a'
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)

@log_start_end(log=logger)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_countries', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('dim_countries', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('dim_data_vendor', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('dim_data_vendor', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('dim_macro_parameters', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('dim_macro_parameters', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_daily_price', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_daily_price', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_foreign_key(None, 'fact_daily_price', 'dim_companies', ['symbol'], ['symbol'])
    op.drop_column('fact_daily_price', 'dividend')
    op.drop_column('fact_daily_price', 'stock_split')
    op.alter_column('fact_economic_calendar', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_economic_calendar', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_income_statement', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_income_statement', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_macro_indicators', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_macro_indicators', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_news', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_news', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_one_min_price', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fact_one_min_price', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('fact_one_min_price', 'adj_close')
    op.alter_column('test', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('test', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###

@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('test', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('fact_one_min_price', sa.Column('adj_close', mysql.FLOAT(), nullable=True))
    op.alter_column('fact_one_min_price', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_one_min_price', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_news', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_news', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_macro_indicators', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_macro_indicators', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_income_statement', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_income_statement', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_economic_calendar', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_economic_calendar', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('fact_daily_price', sa.Column('stock_split', mysql.FLOAT(), nullable=True))
    op.add_column('fact_daily_price', sa.Column('dividend', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'fact_daily_price', type_='foreignkey')
    op.alter_column('fact_daily_price', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fact_daily_price', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('dim_macro_parameters', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('dim_macro_parameters', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('dim_data_vendor', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('dim_data_vendor', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('dim_countries', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('dim_countries', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
