"""empty message

Revision ID: b890ee477745
Revises: 3fd1f3a518f8
Create Date: 2023-08-16 19:58:13.577117

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import logging
from app.decorators import log_start_end


# revision identifiers, used by Alembic.
revision = "b890ee477745"
down_revision = "3fd1f3a518f8"
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


@log_start_end(log=logger)
def upgrade() -> None:
    op.alter_column("fact_daily_price", "volume", type="bigint")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


@log_start_end(log=logger)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
