"""empty message

Revision ID: c36848bdff5e
Revises: 7d270548be60
Create Date: 2023-08-01 21:48:31.388537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c36848bdff5e'
down_revision = '7d270548be60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailypricevendorlink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('data_vendor_id', sa.Integer(), nullable=False),
    sa.Column('daily_price_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_price_id'], ['dim_data_vendor.id'], ),
    sa.ForeignKeyConstraint(['data_vendor_id'], ['fact_daily_price.id'], ),
    sa.PrimaryKeyConstraint('data_vendor_id', 'daily_price_id')
    )
    op.drop_constraint('fact_daily_price_ibfk_1', 'fact_daily_price', type_='foreignkey')
    op.drop_column('fact_daily_price', 'data_vendor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_daily_price', sa.Column('data_vendor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fact_daily_price_ibfk_1', 'fact_daily_price', 'dim_data_vendor', ['data_vendor_id'], ['id'])
    op.drop_table('dailypricevendorlink')
    # ### end Alembic commands ###
