# pylint: disable=unused-import

"""update relationship - securities

Revision ID: e0471ea2c225
Revises: b736f7515117
Create Date: 2023-08-31 12:26:41.229221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0471ea2c225'
down_revision = 'b736f7515117'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
